[package]
authors = ["Paul Severe <pjo2110@columbia.edu>"]
name = "web_dom"
version = "0.1.0"

[dependencies]
cgmath = "0.15.0"
dump = "0.1.1"
euclid = "0.16.0"
stdweb = "0.1.3"
serde = "1"
serde_json = "1"
serde_derive = "1"